### PR TITLE
Draconic Evolution Integration

### PR DESCRIPTION
**Pull request by StevenSeegal**
This is an Integration for the Draconic Evolution's 'Draconic Chest'.
It has 2 smelting features, normal which smelts ore's into single ingot's and an ore doubling mode.
- The 'single' mode is just pulling the recipes form Minecraft's Furnace instance so the Unifying is handled by the 'FurnaceIntegration' already.
- The 'doubling' mode searches the Ore Dictionary and try to force the output to the 'Thermal Foundation' domain.
Therefor I've created this Integration Handler, hoping you'll accept it.

### CODE REVIEW

**Comment by WanionCane** [comment]
I can't believe, in 2 years this is the first time that someone made an Integration for UniDict =D

thanks a lot XD

hey, I would like to ask if it was hard to create it, just to see if I should somehow make it easier =P

**Comment by StevenSeegal** [comment]
To be honest, I had more trouble setting up Intellij as it tried to compile all the libraries and gave me load of errors, found out I could set them to 'provide' and got it working.

The actual implementation took me about 30 minutes to figure out on how to implement it and 15 minutes to write. And tested it for all ore's we have in our pack of course.

Thi Wiki is quite clear on how to implement the Integration and all the existing Integrations giva me a good idea on how to do it. 

Happy to help!

**Comment by WanionCane** [comment]
sorry, it took me one week to have to have time to upload it =/

**Comment by StevenSeegal** [comment]
No problem at all. I'm happy to see it's released now.

**Pull request merged**
