### PR TITLE
Updated for newer EnderIO versions

### PR DESCRIPTION
**Pull request by ElektroKill**
Hello, it's me again!

This time I fixed the UniDict integration for the newer 5.2.62 and higher versions.

Once again thanks for this awesome mod :)

### CODE REVIEW

**Comment by ElektroKill** [comment]
I should probably mention that this change most definitely breaks support for older EnderIO versions

**Comment by WanionCane** [comment]
thank you =D

**Comment by ElektroKill** [comment]
Is there a possibility to release a new version with these changes?

**Comment by WanionCane** [comment]
yeah, I am working on it =P

**Comment by ElektroKill** [comment]
Sorry for saying this in the pr, but I am planing to work on a bigger update for UniDict for version  3.0.0. Is there anything in particular you would want me to change/fix (bugs, outdated integrations, general improvements)?

**Pull request merged**
